version: '3.8'

services:
  megablog:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 